export const DATEREDUCER_CHANGE_CURRENT_YEAR =
    '[DATEREDUCER] CHANGE_CURRENT_YEAR';

export const DATEREDUCER_CHANGE_CURRENT_DAY =
    '[DATEREDUCER] CHANGE_CURRENT_DAY';

export const CHANGE_CURRENT_LANGUAGE =
	'CHANGE_CURRENT_LANGUAGE';