export const DATEREDUCER_CHANGE_CURRENT_YEAR =
    '[DATEREDUCER] CHANGE_CURRENT_YEAR';

export const DATEREDUCER_CHANGE_CURRENT_DAY =
    '[DATEREDUCER] CHANGE_CURRENT_DAY';

export const DATEREDUCER_CHANGE_CURRENT_LANGUAGE =
    '[DATEREDUCER] CHANGE_CURRENT_LANGUAGE';

export const DATEREDUCER_SWITCH_TO_TODAY = '[DATEREDUCER] SWITCH_TO_TODAY';

export const DATEREDUCER_SWITCH_THEME = '[DATEREDUCER] SWITCH_THEME';
